### PR TITLE
Test FirebaseError is raised to caller of FCMDevice methods

### PR DESCRIPTION
**Pull request by henriklindgren**

### CODE REVIEW

**Review by mohitCodepy — APPROVED** [review]
LGTM , Please fix the CI

**Review by mohitCodepy — CHANGES_REQUESTED** [review]
Please fix CI

**Comment by henriklindgren** [comment]
I mocked SendResponse before, should have mocked send of course :sweat: It only worked for me before because I had google auth set up locally

**Review by mohitCodepy — APPROVED** [review]
@henriklindgren , Thanks 😄

**Pull request merged**
